biomejs/website

scripts/README.md

Add a small README file for JS scripts. Also as a self reminder.

docs: add a small README file for JS scripts

---

README.md

To restore the submodule to the commit specified in the remote repository, we should run `pnpm init:biome`.

docs: update README with the correct command

---

netlify.toml
package.json
rust-toolchain.toml

This is a (not so) quick fix for the netlify deployment.
1. Exclude nested git submodules to save some time
2. Disable `wasm-opt` and use `pnpm build:wasm-dev` to save some time
3. Update `rust-toolchain.toml`

fix: netlify deployment

---

astro.config.ts

This PR updates the base URL of the edit link so that it points to this repository instead of the main repository.

chore: update edit link baseUrl

---

rust-toolchain.toml

Keep the rust toolchain in sync with the biome main repo.

chore: symlink `rust-toolchain.toml` to `biome/rust-toolchain.toml`

---

netlify.toml

Set `cache-control` header for the `wasm` file with a bigger `max-age` because we've already been using content hash in filenames for cache busting.

chore: wasm cache control

---

netlify.toml

All files under `/assets/` and `/_astro/` are content-hashed, so we can use a more aggressive `cache-control` strategy for those files.

chore: apply a more aggressive `cache-control` strategy

---

netlify.toml

Netlify will automatically checkout the submodules and it won't fetch nested submodules (which is what we want!). So we don't have to use `pnpm init:biome` anymore.
https://docs.netlify.com/git/repo-permissions-linking/#git-submodules

chore: remove submodule init from build command

---

netlify.toml
scripts/netlify/plugins/wasm-cache/index.js
scripts/netlify/plugins/wasm-cache/manifest.yml

Use [Netlify build plugins](https://docs.netlify.com/integrations/build-plugins/) to cache WASM artifacts. Deployments with the same submodule commit ID will reuse the cached WASM artifacts. Cached artifacts will be preserved for ~30 days.
Skipping the WASM building process will save ~1 min of build time and reduce the build time to ~3min. To further optimize the build time we need to focus on the astro building process.

chore: cache WASM artifacts

---

src/content/docs/recipes/renovate.mdx

Follow up PR after:
- #140
The config example should use valid JSON. The `...` characters are not allowed in JSON files.
Having valid JSON also means that readers can copy/paste the JSON into their `renovate.json` file.
**Edit:** I'm also dropping the word `simply` from the docs. If you need to explain something, it's not simple. Also shorter sentences are easier to read and remember.
> [!TIP]
> If you're copy/pasting the example into your `renovate.json` file, then also add `config:recommended` _or_ `config:best-practices` to the `extends` array. This way Renovate will update your other dependencies as well. But that's a bit off topic for the Biome recipe example, so I'm not putting it in the docs here.

docs: use valid JSON in Renovate config example

---

.github/renovate.json

Attempt to fix crate resolution in [`codegen/Cargo.toml`](https://github.com/biomejs/website/blob/main/codegen/Cargo.toml) in renovate PRs.

chore(ci): enable `cloneSubmodules` for renovate

---

codegen/Cargo.lock
src/content/docs/analyzer/import-sorting.mdx
src/content/docs/guides/migrate-eslint-prettier.mdx

- Add a reference to `noUnusedImports` on the import sorting page
- Add a TLDR on the migration guide

refactor: tldr migratation guide & noUnusedImports ref in import sorting

---

netlify.toml

Skip [OpenGraph images generation](https://github.com/delucis/astro-og-canvas) in deploy previews (i.e. deployments from the PR branches). Deployments from the main branch is unaffected.
The environment variable `SKIP_OG` is used [here](https://github.com/biomejs/website/blob/b90c4acb761433cf08015124f54bd798d5cf4af4/src/pages/og/%5B...path%5D.ts#L7): https://github.com/biomejs/website/blob/b90c4acb761433cf08015124f54bd798d5cf4af4/src/pages/og/%5B...path%5D.ts#L7
This will further reduce the build time.

chore(ci): skip og in deploy previews

---

src/pages/playground.astro

Pass the correct framework to `client-only` directive.
https://docs.astro.build/en/reference/directives-reference/#clientonly

fix(client-directive): `client-only`

---

.github/workflows/file-change-guard.yaml

This PR adds a workflow to check for submodule mutations in a PR. In general, the submodule shouldn't be mutated by users except for `github-actions[bot]`.
If submodule mutations from users are detected in a PR, the check for that PR will fail.
> [!NOTE]
> Checks cannot be applied to PRs created by `github-actions[bot]`. This is an expected behavior: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

chore(ci): guard submodule mutation

---

src/pages/schemas/1.7.2/schema.json.js

Fixes a small rule name typo in schema v1.7.2

Fix rule name typo in schema

---

src/content/docs/guides/big-projects.mdx

Fix Monorepos config examples. It is incorrect that `rules` appears twice.

docs: Fix typo in Monorepos example

---

codegen/src/lintdoc.rs
src/content/docs/linter/rules/no-confusing-labels.md
src/content/docs/linter/rules/no-unused-labels.md

Support `astro`, `svelte` and `vue` code blocks in lint docs to pass the tests.

fix(codegen): support embedded kind code blocks

---

codegen/src/website.rs

There may be the case where `schema_version_folder_path` exists but `schema_js_path` does not, which will fail the codegen script. So this PR switches to use `fs::remove_dir_all` to forcely delete the stale schema folder.

chore(ci): make codegen more robust

---

.github/renovate.json

This repo itself uses biome, so we use [`regexManagers:biomeVersions`](https://docs.renovatebot.com/presets-regexManagers/#regexmanagersbiomeversions) to keep the schema updated.

chore(ci): update renovate config with `regexManagers:biomeVersions`

---

src/frontend-scripts/util.ts
src/playground/Playground.tsx

I noticed that when the theme is selected as `Auto`, the playground editors still uses the light theme when the page first loads: https://deploy-preview-227--biomejs.netlify.app/playground/
This issue is caused by the [recent refactor of the starlight component `<ThemeSelector>`](https://github.com/withastro/starlight/pull/1734/files).

fix(editor): auto theme

---

codegen/src/lintdoc.rs

fix: jsx runtime regression

---

.gitattributes

Adds `metadata/` as auto-generated

chore: mark file as autogenerated

---

.github/renovate.json
src/content/docs/recipes/renovate.mdx

Renovate renamed `regexManagers` with `customManagers` recently: https://github.com/renovatebot/renovate/pull/28979
The hyperlink to `renovatebot.com` does not work anymore. Time to update the docs?

refactor: replace `regexManagers` with `customManagers`

---

codegen/src/lintdoc.rs
src/content/docs/linter/rules/no-banned-types.md
src/content/docs/linter/rules/no-static-only-class.md
src/content/docs/linter/rules/use-naming-convention.md

Fix the documentation generation to handle correctly nested list.
This is a permanent correction for the PR #307 
It also add `HardBreak` (double space at the end of a line) in the markdown parser
It also linked to the PR https://github.com/biomejs/biome/pull/2875

fix: Add better handling of markdown list

---

src/content/docs/formatter/index.mdx

Update CLI anchor link
Due to a minor error the link to the CLI redirects to a page that does not exist

Update CLI anchor link in Formatter section

---

src/content/docs/linter/index.mdx

Make it clear that in order to disable **all linter rules**, one can use the `linter.rules.recommended = false` option.
Based on https://github.com/biomejs/biome/discussions/2822

chore: clarify how to disable all rules

---

netlify.toml
package.json
scripts/netlify/plugins/wasm-cache/index.js

- Remove `SKIP_WASM_BUILD_FILE_PATH` because we can directly check the existence of the `.wasm` file.
- Reduce the netlify WASM build cache duration from 30 days to 3 days. Aggressive caching can increase the download size and coldstart time significantly. 30 days is too long.
- Change the wasm-pack `--scope` from `biomedev` to `biomejs`. Idealy the package name should be also changed from `biome_wasm` to `wasm-web`, however this will not affect the website because we explicitly set the filepath to resolve the package, so I just leave it as is.

chore(scripts): some housekeeping chores

---

scripts/netlify/plugins/wasm-cache/index.js

Don't skip WASM build if `@biomejs/wasm-web` has stale `.wasm` files.

chore(ci): fix WASM cache behavior

---

codegen/src/metadata.rs
src/pages/metadata/rules.json.js

Exposes the documentation URL in the rule metadata, so that anything that uses the metadata (basically biomebot :P) doesn't have to apply kebab-case to the rule name itself

feat(metadata): add `link` to rules

---

src/content/docs/linter/index.mdx

Fixed a broken link for the **noDebugger** rule in the Linter Rules documentation. Fixes issue #415

chore: update/fix link in linter documentation

---

src/content/docs/guides/integrate-in-vcs.mdx

Use backticks correctly
There's two typos in the paragraph where a single quote is used instead of a backtick.

docs: Fix typo

---

src/content/docs/ja/recipes/git-hooks.mdx
src/content/docs/pt-br/recipes/git-hooks.mdx
src/content/docs/zh-cn/recipes/git-hooks.mdx

I found a typo on the Japanese page at https://biomejs.dev/ja/recipes/git-hooks/.
While the English page correctly uses "push_files" at https://biomejs.dev/recipes/git-hooks/, the Japanese page mistakenly uses "pushed_files."
I checked the following page, which indicates that "push_files" is the correct term, so I have made the necessary correction:
https://github.com/evilmartians/lefthook/blob/a58c11d76d087a5d0bfd2259e41f61e0007cbaa0/docs/configuration.md#push_files-template

fix: git-hooks typos

---

src/content/docs/reference/configuration.mdx

javascript section has an incorrect json argument.
❌wrong:
javascript
json.linter.enabled
✔️correct:
javascript:
javascript.linter.enabled

docs: typo `javascript.linter.enabled` at configuration

---

src/content/docs/reference/configuration.mdx

`css.formatter.indentSize` was renamed `css.formatter.indentWidth` at https://github.com/biomejs/biome/pull/2790.
Unlike the other deprecated indentSize options (e.g. [formatter.indentSize](https://biomejs.dev/reference/configuration/#formatterindentsize)),
`css.formatter.indentSize` doesn't work anymore.
That's why `css.formatter.indentSize` should be deleted.

docs: delete `css.formatter.indentSize` param

---

src/content/docs/reference/configuration.mdx

The `javascript.formatter.trailingComma` option is deprecated and renamed to `javascript.formatter.trailingCommas`.
Then add the configuration.
Details can be checked in https://github.com/biomejs/biome/pull/2492

docs: add `javascript.formatter.trailingCommas`

---

.github/actions/setup-rust-toolchain/action.yaml
src/playground/workers/biomeWorker.ts

We used to put the `Cargo.toml` file into the `codegen` subdir and I used a small hack to let it cache the target directory properly back then. Now we moved the manifest file to the root, so we no longer need the hack.
I also deleted all the actions cache.

fix(ci): setup-rust cache

---

.github/workflows/run-codegen.yaml

chore(ci): remove revision input from the codegen step

---

.github/workflows/ja-translation.yaml
.github/workflows/synchronize.yaml
.github/workflows/update-contributors.yaml
.node-version

- Add a `.node-version` file so netlify can also use the same version of node to build the site.
- Disable the pnpm cache. It's taking up the space and I don't think it will have too much effect. Let's see.

chore(ci): add `.node-version` file and disable pnpm cache

---

Cargo.lock
Cargo.toml
package.json
pnpm-lock.yaml
scripts/update-revision.sh

Run `cargo update` to update the lock file to fix the errors when rust dependencies are bumped in the main repo: https://github.com/biomejs/website/actions/runs/9443240377/job/26006649009#step:10:128

chore(ci): fix cargo deps

---

codegen/src/lintdoc.rs
codegen/src/metadata.rs

Following https://github.com/biomejs/biome/pull/3152, this PR removes the code that checks the validity of the documentation. Now the code prints markdown.

ci(codegen): remove diagnostics check from codegen

---

src/content/docs/guides/getting-started.mdx
src/content/docs/guides/how-biome-works.mdx
src/content/docs/internals/changelog.md
src/content/docs/ja/guides/getting-started.mdx
src/content/docs/pt-br/guides/getting-started.mdx
src/content/docs/reference/configuration.mdx
src/content/docs/zh-cn/guides/getting-started.mdx
src/content/docs/zh-cn/reference/configuration.mdx
src/pages/schemas/1.8.1/schema.json.js

Updates the website for 1.8.1 release

release: 1.8.1

---

codegen/src/lintdoc.rs

Some rules require this information to correctly emit diagnostics.

fix(ci): provide file_path info to lintdoc analyze

---

.github/workflows/integrate.yaml
astro.config.ts
src/content/docs/guides/editors/create-a-plugin.mdx
src/content/docs/guides/editors/first-party-plugins.mdx
src/content/docs/guides/editors/third-party-plugins.mdx

This PR breaks down the`/guides/editors` page into three pages:
- first party plugins
- third party plugins
- integrate Biome into a plugin
I broke it down because I plan to add more information inside the last page. There's way more stuff that we can add, but it requires some generated code that I hope to pull off. 
I added `zed` to the list of first party plugins

refactor: break down editors pages

---

.npmrc
astro.config.ts

Shiki doesn't recognize `cjs` code blocks, it will fallback to render them as `plaintext`.
For example: https://biomejs.dev/linter/rules/no-redundant-use-strict/
Also check the deployment log: https://app.netlify.com/sites/biomejs/deploys/666c5e50c6f7750008bb8102#L143-L156
I patched the astro config to load the js grammar for `cjs` codeblocks.

fix: syntax highlighting for cjs code blocks

---

Cargo.lock
Cargo.toml
codegen/src/lintdoc.rs
package.json
pnpm-lock.yaml
src/playground/Playground.tsx
src/playground/utils.ts
src/playground/workers/biomeWorker.ts

This PR updates the frontend to support `.graphql` and `.gql` files, however the playground is throwing an error.
This is probably a bug  in core, I will look after it.

feat: support for graphql files

---

src/playground/workers/biomeWorker.ts

This PR enableds `pullDiagnostics` for GraphQL, which is now supported by WASM. This allows us to print parse diagnostics in the console!

feat: enable `pullDiagnostics` for graphql

---

src/content/docs/recipes/git-hooks.mdx

Script was preventing if there _isn't_ a `MM`, should be the other way around.

docs: fix shell script git hook

---

src/playground/CodeMirror.tsx
src/playground/Playground.tsx
src/playground/components/DiagnosticsPane.tsx
src/playground/tabs/DiagnosticsListTab.tsx
src/playground/utils.ts

In Rust we use [UTF-8 ***byte*** offsets](https://github.com/biomejs/biome/blob/c372484473b64c9c84ad3361d71b2c419345b45b/crates/biome_text_size/src/size.rs#L13) for `TextSize`, which will be used in `TextRange` and ultimately be passed to the JavaScript side as the numbers in `diagnostic.location.span`. However, in JavaScript, we use [UTF-16 ***code unit*** offsets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#instance_methods) to access the characters.
So when a character is represented by multiple bytes in UTF-8 encoding and is placed before or is part of the code that triggers a diagnostic, the playground will wrongly interpret its byte offset as a code unit offset, thus causing an out of bounds indexing error when it tries to highlight the …

fix(playground): multi-byte character issue

---

src/content/docs/formatter/index.mdx

Update the example config to use `javascript.formatter.trailingCommas`

docs: Fix use of deprecated `trailingCommas` in biome.json example

---

src/content/docs/recipes/badges.mdx

If people are wanting to include these badges in their readmes it's because they think it's important that people are familiar with the toolchain that's being used, in case people are not familiar a link is probably what they want

Include links in badges

---

src/styles/_overrides.scss

- When hovering home page cards I noticed slight layout shift. Fix it by keeping border stable and only changing color on hover.
- Also remove some duplicated styles inside `_overrides.scss`.
Before:
https://github.com/biomejs/website/assets/8914032/746e7c62-a96a-4ef1-9c98-7308fca72bd9
After:
https://github.com/biomejs/website/assets/8914032/0cdd3a2d-af21-4266-bce6-392ebc8c5c11

fix: prevent layout shift when hovering home page cards

---

src/content/docs/ja/internals/language-support.mdx

Updated Japanese translation of the Language Support.

docs: Update Japanese Language Support

---

src/content/docs/internals/language-support.mdx

Remove Astro globals section because we do [include it by default](https://github.com/biomejs/biome/pull/3006).
Add `useImportType` and `noUndeclaredVariables` to rules which should be disabled when using htmlish languages.
https://github.com/biomejs/biome/discussions/3426

docs: document few more rules not working for htmlish languages

---

src/content/docs/internals/language-support.mdx

In https://github.com/biomejs/website/pull/787 I incorrectly documented `noUndeclaredVariables` as not working properly on htmlish languages, I had did disabled in one of my projects before, likely to deal with globals, but that is not needed.

docs: remove noUndeclaredVariables from htmlish rules limitations list

---

src/content/docs/linter/index.mdx

docs: fix spelling mistake in linter docs

---

src/playground/workers/prettierWorker.ts

Make it easy to compare the formatting of template strings

chore(playground/prettier): turn off embedded language formatting

---

src/content/docs/guides/configure-biome.mdx

There is a small typo on the "Configure Biome" page.

fix: typo on "Configure Biome" page

---

src/content/docs/zh-cn/recipes/git-hooks.mdx

> Detected incorrect braces with only single value: `**.{js|ts|cjs|mjs|d.cts|d.mts|jsx|tsx|json|jsonc}`. Reformatted as: `**.js|ts|cjs|mjs|d.cts|d.mts|jsx|tsx|json|jsonc`
Got warn when running `git commit`，reformat the extends

fix(zh-cn): git-hooks/lint-staged extends Reformatted

---

src/content/docs/linter/rules/use-filenaming-convention.md

Correct the "override" example in https://biomejs.dev/linter/rules/use-filenaming-convention/.

fix `use-filenaming-convention` override example

---

src/content/docs/linter/rules/use-filenaming-convention.md

Currently the example configuration which [describes overriding of ignoring file name conventions](https://biomejs.dev/linter/rules/use-filenaming-convention/#ignoring-some-files) is missing a nesting of `rules`. This pull requests adds it to show how it can be applied.

docs: fix example configuration of `useFilenamingConvention` to ignore some files

---

src/content/docs/ja/recipes/git-hooks.mdx
src/content/docs/pt-br/recipes/git-hooks.mdx
src/content/docs/recipes/git-hooks.mdx
src/content/docs/zh-cn/recipes/git-hooks.mdx

https://github.com/biomejs/website/issues/872
> The git error log output by Lefthook outputs ANSI escape code as is, so we need to add an option to display plain text.
> It took me a little while to get to this information, but wouldn't it be more helpful to include it by default in the Lefthook Example in the Git Hook section?

docs(Git Hooks): add colors option for lefthook example :memo:

---

src/content/docs/guides/configure-biome.mdx

Example generates error in Biome version 1.8.3 
```text
Couldn't parse the src/**.js, reason: recursive wildcards must form a single path component
```
There should be single `*.js` instead of `**.js`

Fix example with `files.include` example to avoid Couldn't parse error

---

src/playground/workers/prettierWorker.ts

Sometimes the message contains useful info, and displaying it upfront provides a slightly better DX.

feat: slightly better error messages from prettier

---

astro.config.ts
src/content/docs/reference/gritql.mdx

This adds a GritQL reference. Going forward, documentation related to `biome search` should point to this page instead of directly to grit.io.

Add reference for GritQL

---

src/pages/blog/[...slug].astro

The "Edit page" links at the bottom of blog posts on the website go to the presumably old location of this website codebase, this updates it to correctly go to this repository (the structure has not changed so this simple fix works).

fix: update blog post edit link

---

.github/actions/free-disk-space/action.yml
.github/workflows/synchronize.yaml

Tries to add a clean space CI job. The sync job fails due to not enough disk space

ci: clean disk space to fix sync job

---

.github/ISSUE_TEMPLATE/config.yaml
astro.config.ts
src/components/ExternalLinks.astro
src/content/blog/annoucing-biome.mdx
src/content/blog/biome-v1-7.md
src/content/docs/guides/getting-started.mdx
src/content/docs/index.mdx
src/content/docs/internals/philosophy.mdx
src/content/docs/ja/guides/getting-started.mdx
src/content/docs/ja/index.mdx
src/content/docs/ja/internals/philosophy.mdx
src/content/docs/pt-br/guides/getting-started.mdx
src/content/docs/pt-br/index.mdx
src/content/docs/pt-br/internals/philosophy.mdx
src/content/docs/zh-cn/guides/getting-started.mdx
src/content/docs/zh-cn/index.mdx
src/content/docs/zh-cn/internals/philosophy.mdx

This PR replaces the discord invite link to `https://biomejs.dev/chat`, which is a simple redirect to the discord link

chore: use `/chat` URL

---

src/content/blog/biome-v1-6.mdx

`The property trailingComma is deprecated. Use javascript.formatter.trailingCommas instead. biome(deserialize)`
This commit updates the code sample to be up-to-date.

fix: example config was using a deprecated key

---

src/components/PackageManagerCommand.astro
src/content/docs/guides/getting-started.mdx
src/content/docs/ja/guides/getting-started.mdx
src/content/docs/pt-br/guides/getting-started.mdx
src/content/docs/zh-cn/guides/getting-started.mdx

Adds the deno install script according to its [documentation](https://docs.deno.com/runtime/reference/cli/install/) to have support for all the package managers.
It does not appear that deno has an equivalent to the --exact flag.

Add Deno installation script

---

src/content/docs/analyzer/import-sorting.mdx

Currently, the documentation states that import sorting can be done using the `biome check` command with the `--write` option. As `--write` doesn't exist as a valid option, I changed it to the actual option that does the sorting - `--apply`

Import Sorting Docs - Replace `--write` with '--apply'

---

codegen/src/lintdoc.rs

refactor: remove unused lifetime `'a`

---

src/content/docs/ja/internals/language-support.mdx

Currently, there are some differences between the language support page in Japanese and the English one. (See also: https://github.com/biomejs/website/pull/787)
This PR resolves those differences.
I also fixed typo in the language support table.

docs: Update language support page (Japanese) with the latest information

---

.gitignore

Depending on your checkout method and setup (for example, within a VS Code DevContainer), `pnpm` creates a `.pnpm-store` folder at the root of your workspace that should be ignored by `git`.
Not ignoring it can cause quite a headache and >10,000 untracked changes due to files in `.pnpm-store`.

fix(gitignore): add `.pnpm-store` to `.gitignore`

---

src/content/docs/ja/reference/configuration.mdx

I read Japanese docs and found jsxRuntime codeBlock write twice. So I remove that.

Remove duplicate code block in JA docs

---

src/content/docs/fr/guides/manual-installation.mdx

Add the translation into French of the “Manual installation” page.
Added:
- the `guides/getting-started.mdx` file translated into French.

docs: add French translation of guides/manual-installation.mdx

---

astro.config.ts
src/components/starlight/SiteTitle.astro
src/content/docs/index.mdx
src/pages/support.astro

This adds a page for commercial support to our website:
The page is also linked to from the front page (I've removed the rather non-specific "Optimized" section):
Note that the link in the card for this doesn't work yet. I suspect it's a CSS issue, but I didn't yet see the source of the issue :thinking: 
Let me know what you think!

Commercial support page

---

astro.config.ts

While reading the documentation on the Biome website, I noticed that the phrase "配置生物群落" in the left-side menu seemed quite odd and out of context. Upon checking the original English text, I found that it was meant to be "Configure Biome." This discrepancy suggests that the translation may have been inaccurately generated by a machine translation tool.

fix(docs): fix the incorrect Chinese translation

---

src/content/docs/reference/configuration.mdx

This fixes a incorrectly documented option for `formatter.attributePosition` and `javascript.formatter.attributePosition`
Currently it says it will always format the attributes to multiline, however if only 1 attribute is used it will format it inline rather then multiline.
This changes explicitly explains that it will only format and collapse to multiline if more then 1 attribute is used.
closes #1682

fix: changes text for multiline attributePosition

---

src/content/docs/reference/cli.mdx

1. remove `examples` section and move code blocks to the `usage` section
2. make the page outline clearer

docs: update CLI examples for clarity and consistency

---

src/content/docs/guides/manual-installation.mdx

This PR adds instructions for using the official Docker images for Biome.
Ref: https://github.com/biomejs/docker

feat: add docker instructions

---

src/content/docs/ja/reference/vscode.mdx
src/content/docs/pt-BR/reference/vscode.mdx
src/content/docs/reference/vscode.mdx
src/content/docs/zh-CN/reference/vscode.mdx

Our company recently added biome, and set up vscode autofixes as described in the [existing docs](https://biomejs.dev/reference/vscode/#fix-on-save). We immediately hit the issue described here https://github.com/biomejs/biome-vscode/issues/229, which was very painful in a repo of our size.
It seems like `source.fixAll.biome` is a strictly better setting to recommend than `quickfix.biome`, so this PR swaps all existing references out for the former.

docs(vscode): suggest faster source.fixAll.biome setting instead of quickfix.biome for vscode config

---

.github/workflows/playwright.yml
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts

This PR updates the playground so that it's compatible with the changes currently on `next` in the main Biome repo. It needs to be merged after biomejs/biome#4760. The goal for this PR is to simply make the playground functional for 2.0, not to add new features to support new 2.0 functionality.
To test this, I've been using the following command to build the wasm bin and copy over to this repo's `node_modules`:
```
wasm-pack build --dev --out-dir ../../packages/@biomejs/wasm-web --target web --scope biomejs crates/biome_wasm --features experimental-html && cp -v packages/@biomejs/wasm-web/* ../biome-website/node_modules/@biomejs/wasm-web
```

refactor(playground): upgrade playground to be compatible with biome 2.0

---

src/playground/Playground.tsx
src/playground/PlaygroundLoader.tsx
src/playground/tabs/ImportSortingTab.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts

This fully removes the import sorting tab and makes the UI changes necessary to show "Assist" instead of "Import sorting".
It also adds UI for being able to specify rule domains. I'm not entirely sure what to do with the `Lint Rules` option though. Open to suggestions.
> [!CAUTION]
> This PR is stacked on the following PRs. **Do not merge it without merging the others and rebasing this branch.** To review this PR, look at the last commit only.
> - #1722

feat(playground): remove import sorting tab, rename import sorting to assist, add rule domains

---

src/playground/PlaygroundLoader.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts
src/playground/workers/prettierWorker.ts

Adds HTML specific formatter options to the playground's settings. I've verified that they get passed into both biome and prettier's configuration. It won't be obvious it's working for biome's formatter because the logic for these options isn't entirely complete in biome.
> [!CAUTION]
> This PR is stacked on the following PRs. **Do not merge it without merging the others and rebasing this branch.** To review this PR, look at the last commit only.
> - #1727

feat(playground): add html formatter options

---

package.json
pnpm-lock.yaml
src/playground/PlaygroundLoader.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts
src/playground/workers/prettierWorker.ts

Added `objectWrap` options to the playground. Also I updated Prettier to v3.5.1 (latest) to get `objectWrap` support on Prettier that was introduced in v3.5.0.

feat: add objectWrap option to the playground

---

.github/renovate.json
.textlintrc.json
biome.json
lunaria.config.json
scripts/package.json
src/content/docs/reference/configuration.mdx
tsconfig.json

Closes https://github.com/biomejs/website/issues/1760
Closes https://github.com/biomejs/website/issues/1763
Closes https://github.com/biomejs/website/issues/1761
This PR updates the configuration reference page:
- added `graphql` and `grit` options
- added `javascript.parser.jsxEverywhere`
- added `json.formatter.expand`
- added the new configuration that can be assigned to a group
- removed options that were removed from v2
- added more JSON examples 
- Changed `CSS (and super languages)` to `CSS` because that's misleading. Plus, we removed it from the CLI too

feat: document new options (no domains yet)

---

src/playground/Playground.tsx
src/playground/PlaygroundLoader.tsx
src/playground/components/DiagnosticsPane.tsx
src/playground/components/Tabs.tsx
src/playground/tabs/ImportSortingTab.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts

Closes #1785 
The playground is broken now, so I updated it to follow the breaking changes will be introduced in Biome v2.0. I removed the "Import Sorting" tab for now, it will be available again as the "Assist" view.

fix: update WASM API usages for Biome v2.0

---

src/content/docs/guides/editors/third-party-extensions.mdx

Add an extension for Nova in the Third-party extensions list
Updated:
- src/content/docs/guides/editors/third-party-extensions.mdx

docs: add nova extension

---

src/playground/PlaygroundLoader.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts
src/playground/workers/prettierWorker.ts

Added a new option `expand` to the playground settings.
Removed `objectWrap` as it was merged into `expand`.
See https://github.com/biomejs/biome/pull/5262 for details.

feat(playground): add the `expand` option to the playground

---

src/playground/PlaygroundLoader.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts
src/playground/utils.ts

In single-file mode, it was not able to change the file language, especially for non JavaScript-like files (JSON, CSS, etc.). I added a language selector to change the file language quickly. Defaults to `TSX`.

feat(playground): add language selector for single-file mode

---

src/playground/components/EnumSelect.tsx
src/playground/tabs/SettingsTab.tsx

As @ematipico suggested in https://github.com/biomejs/website/pull/1811#discussion_r1986034650, it will be great if we can check all variants in enums are covered by the corresponding `<select>` element. I added a new component `<EnumSelect>` as a type-safe wrapper and replaced all `<select>`s to the new component.
For example, tsc will emit an error when we added a new language in the enum but not yet in the `<EnumSelect>`:

refactor(playground): add `EnumSelect` component to ensure all options are covered

---

.github/workflows/integrate.yaml
codegen/src/domains.rs
package.json
src/playground/PlaygroundLoader.tsx
src/playground/tabs/SettingsTab.tsx
src/playground/types.ts

Synced to pull the changes from biomejs/biome#5306 and biomejs/biome#5308, then fixed typing issues using the generated `RuleDomains` type. Plus, I added a `tsc` step to the workflow to ensure the code is valid in TypeScript on every PR.

fix(playground): use generated `RuleDomains` type to fix typing issues

---

astro.config.ts

Removed the duplicated section from the top-level menu in favour of the second-level one in the tools section.

fix: remove duplicated formatter section from menu

---

astro.config.ts
src/content/docs/reference/gritql.mdx

I was thought it it not available yet, but it's already available in v1.9.4.
Reverted the part of changes from #1858.

fix: revert GritQL doc removal as it's already available in v1.9.4

---

src/playground/workers/biomeWorker.ts

The html formatter has been disabled by default in https://github.com/biomejs/biome/pull/5354, we need to explicitly enable it in the playground.

fix(playground): enable html formatter on the playground

---

astro.config.ts
src/content/docs/reference/vscode.mdx

This PR updates the VS Code reference for the v3 release.

feat: release vs code extension v3

---

astro.config.ts
src/components/starlight/LanguageSelect.astro

Add a version selector for redirecting to the v2.0 beta documentation.
Not sure this is the right way in Astro + Starlight, I added the selector into the `LanguageSelect` component as `starlight-blog` does for [`ThemeSelect`](https://github.com/HiDeoo/starlight-blog/blob/3f9e45506b240a6c837e0f601b9cf865ca6473e1/packages/starlight-blog/overrides/ThemeSelect.astro).

feat: add version selector as the link to next.biomejs.dev

---

astro.config.ts
src/content/docs/blog/biome-v2-0-beta.md
src/content/docs/linter/plugins.mdx

As we no longer have the analyzer section in Biome v2.0, plugins should have the new place to live in. I renamed "Analyzer Plugins" to "Linter Plugins" and moved to the linter section.

fix(docs): move Analyzer Plugins to Linter Plugins

---

src/content/docs/fr/guides/editors/third-party-extensions.mdx

Add the translation into French of the “Third-party-extensions” page.
Added:
- the `guides/editors/third-party-extensions.mdx` file translated into French.

docs: add French translation of guides/editors/third-party-extensions.mdx

---

src/content/docs/fr/guides/editors/first-party-extensions.mdx

Add the translation into French of the “First-party-extensions” page.
Added:
- the `guides/editors/first-party-extensions.mdx` file translated into French.

docs: add French translation of guides/editors/first-party-extensions.mdx

---

src/content/docs/fr/guides/big-projects.mdx

Add the translation into French of the “Use Biome in big projects” page.
Added:
- the `guides/big-projects.mdx` file translated into French.

docs: add French translation of guides/big-projects.mdx

---

src/content/docs/fr/guides/getting-started.mdx

Add the translation into French of the “Getting started” page.
Added:
- the `guides/getting-started.mdx` file translated into French.

docs: add French translation of guides/getting-started.mdx

---

src/content/docs/fr/reference/vscode.mdx

Add the translation into French of the “VSCode extension” page.
Added:
- the `reference/vscode.mdx` file translated into French.

docs: add French translation of reference/vscode.mdx

---

src/content/docs/fr/analyzer/import-sorting.mdx

Add the translation into French of the “Imports sorting” page.
Added:
- the `analyzer/import-sorting.mdx` file translated into French.

docs: add French translation of analyzer/import-sorting.mdx

---

src/content/docs/fr/reference/diagnostics.mdx

Add the translation into French of the Diagnostics page.
Added:
- the `reference/diagnostics.mdx` file translated into French.

docs: add French translation of reference/diagnostics.mdx

---

src/content/docs/fr/formatter/index.mdx

Add the translation into French of the Formatter page.
Added:
- the `formatter/index.mdx` file translated into French.

docs: add French translation of formatter/index.mdx

---

src/content/docs/fr/formatter/differences-with-prettier.md

Add the translation into French of the “Differences with Prettier” page.
Added:
- the `formatter/differences-with-prettier.md` file translated into French.

docs: add French translation of formatter/differences-with-prettier.md

---

src/content/docs/fr/reference/reporters.mdx

Add the translation into French of the Reporters page.
Added:
- the `reference/reporters.mdx` file translated into French.

docs: add French translation of reference/reporters.mdx

---

src/content/docs/fr/linter/index.mdx

Add the translation into French of the Linter page.
Added:
- the `linter/index.mdx` file translated into French.

docs: add French translation of linter/index.mdx

---

astro.config.ts
src/content/docs/zh-CN/guides/editors/create-a-extension.mdx
src/content/docs/zh-CN/guides/editors/first-party-extensions.mdx
src/content/docs/zh-CN/guides/editors/third-party-extensions.mdx

Add the translation into Chinese of the editor extension page.
Added:
- guides/editors/first-party-extensions.mdx
- guides/editors/third-party-extensions.mdx
- guides/editors/create-a-extension.mdx
And translated related sidebar menu in `astro.config.ts`

Add Chinese Translation of editor extensions integration

---

src/pages/enterprise.astro

- The icon heart is a bit bigger
- The text inside the banner matches the rest of the page (it was too small)
- The border radius of the CTAs matches the ones of the home page
- The borders of the containers matches the ones of the entire page
- The CTAs have an external icon
- The link of the CTA that points to GitHub now points directly to the correct template

chore: enterprise page tweaks

---

astro.config.ts
lunaria.config.json

Adding i18n support for Spanish (#2018) to the projects config files.

chore: add Spanish i18n support to config

---

src/content/docs/reference/configuration.mdx

fix small typo in `configuration.mdx`

docs: fix small typo in `configuration.mdx`

---

src/content/docs/es/linter/plugins.mdx
src/content/docs/ja/linter/plugins.mdx
src/content/docs/linter/plugins.mdx

I'm playing around with the plugin API in the beta version of `v2`.
I noticed a small discrepancy in the documentation after testing the following GritQL code:
```gritql
language js;
`describe($object.$property, $rest)`
where {
$property <: `name`,
register_diagnostic(
span = $property,
message = "Don't use `.name` - Vitest will use this property automatically",
severity = "information"
)
}
=> `describe($object, $rest)`
```
The compilation part didn't work because of the value in `severity`.
Following the source code:
https://github.com/biomejs/biome/blob/2333c7ad5ab1cd626dcc5dfe6049633340cd7252/crates/biome_diagnostics/src/diagnostic.rs#L137-L151
Renaming:
`information` -> `info`
`warning` -> `warn`
I also renamed it in the other languages, which have already translated the page, so I …

docs(linter/plugins): Correct available names of the severity diagnostic

---

lunaria.config.json

This issue is caused by #1600. The `rootDir` in `lunaria.config.json` is set to `src/content/docs`, which results in all commit history URLs in the [i18n dashboard](https://biomejs.dev/i18n-dashboard/) being incorrect. For example:
```
https://github.com/biomejs/website/blob/main/src/content/docs/src/content/docs/ja/guides/editors/third-party-extensions.mdx
```
(Note the duplicated `src/content/docs`.)

fix(lunaria): remove error root dir

---

astro.config.ts
src/content/docs/es/linter/index.mdx
src/content/docs/es/reference/configuration.mdx

This should fix the failing builds for the `next` branch, but it avoids updating the spanish content to match the english one because I don't know spanish.
cc @ernieMrtnz : Would you mind making another PR for `src/content/docs/es/linter/index.mdx` on the `next` branch? That page has changed significantly.

fix(es): update imports and links

---

src/playground/Playground.tsx
src/playground/tabs/SemanticModelTab.tsx
src/playground/types.ts
src/playground/workers/biomeWorker.ts

Expose a new tab for the semantic model debug printer. This will not work until https://github.com/biomejs/biome/pull/5821 is merged, and this PR is rebased to include it.

feat(playground): add semantic model tab

---

src/pages/schemas/2.0.0-beta.2/schema.json.js

Fixes biomejs/biome#5831 and biomejs/biome#5908
Some users have complained about the missing schema for 2.0.0-beta.2. The `$schema` added by `biome migrate` refers one under `biomejs.dev`, which is not available, while it's available under `next.biomejs.dev`. We should host the schema under `biomejs.dev` too.

feat: add JSON schema for 2.0.0-beta.2

---

src/styles/playground/_tabs.css

Fixed CSS to remove bullets and unnecessary padding from the tabs list.
Before
After

fix: remove unnecessary bullets from the playground tabs

---

src/content/docs/es/internals/language-support.mdx
src/content/docs/fr/internals/language-support.mdx
src/content/docs/internals/language-support.mdx
src/content/docs/ja/internals/language-support.mdx

https://github.com/biomejs/biome/issues/6049 alerted us that this page was outdated. I've fixed the snippet at the end to use the new `includes` and the correct globs. I've also added a couple new rules that I've found need to be disabled via dogfooding biome on my own projects.

docs: update override snippet for partial vue/svelte/astro support

---

src/playground/workers/biomeWorker.ts

Fixed the `Workspace#openProject` call to extract the project key from the result, as the interface was recently changed in https://github.com/biomejs/biome/pull/6099.

fix(playground): extract projectKey from OpenProjectResult

---

src/content/docs/guides/big-projects.mdx

The docs suggest using the key `include` in the `overrides` array in the monorepo section. The correct key is `includes` (with a s)

fix: correct key in overrides in monorepo docs

---

package.json
pnpm-lock.yaml
src/pages/api/versions.ts
src/pages/api/versions/latest.ts

This PR introduces two new API endpoints for retrieving both the list of all Biome versions and the latest version. The purpose of these endpoints is to make it easier for first-party tooling to list and find those versions.
Both endpoints support content negotiation to serve either JSON (default) or plain text, depending on whether the `Accept` header is set to `text/plain` or `application/json`.
The `/api/versions` endpoint returns the list of all Biome versions, sorted in descending order (latest first). By default it only includes stable versions, but pre-release versions can be included with `?prereleases=true`
```sh
curl https://biomejs.dev/api/versions
curl -H 'Accept: text/plain' https://biomejs.dev/api/versions
curl https://biomejs.dev/api/versions?prereleases=true
curl -H …
```

feat(api): add versions endpoints

---

src/components/starlight/Hero.astro
src/content/docs/es/index.mdx
src/content/docs/fr/index.mdx
src/content/docs/index.mdx
src/content/docs/ja/index.mdx
src/content/docs/pt-BR/index.mdx
src/content/docs/uk/index.mdx
src/content/docs/zh-CN/index.mdx

This removes the background grid from the hero on the landing page.
I removed the background grid from the hero section because it made the overall design feel too busy and visually overwhelming.
By simplifying the background, the hero section now feels more focused and clean, allowing the headline and call-to-action to stand out more effectively.

style: remove hero grid

---

src/content/docs/reference/zed.mdx

Biome's previous recommend Zed settings include settings which were not language scoped, as a result, users regularly reported broken formatters for non-biome supported languages (Rust, etc).  It also means that biome-language-server **always** runs which is not a good default.
You'll notice that all the examples in the Zed Docs are scoped to an individual language, ex:
- https://zed.dev/docs/configuring-languages#configuring-formatters (`formatter`)
- https://zed.dev/docs/configuring-languages#choosing-language-servers (`language_servers`)
- https://zed.dev/docs/configuring-languages#setting-up-linters (`code_actions_on_format`)
I understand this is more verbose but it is also more explicit.
Let me know if there's anything I should do to the translated versions of the docs (e.g. remove …

Zed: Switch configuration from global to language specific

---

src/content/docs/recipes/continuous-integration.mdx

**Add documentation note for using external packages with Biome CI action**
This improves the CI recipe documentation by adding a note on handling Biome configs that rely on external dependencies/configs. It includes a snippet showing how to set up Node.js and install dependencies before running biome ci.

docs: add note about external packages in conjunction with biome action

---

src/content/docs/guides/upgrade-to-biome-v2.mdx

In the example for "Paths and globs are now relative to the configuration file", both `src` directories are at the same level in the `FileTree`. This moves `ui/src` to nest correctly under `ui`
Sorry about the inconsequential final line diff, I edited through github UI and that was performed automatically. If you would like me to remake without that I am happy to

fix: nest ui/src properly in relative globs example

---

src/content/docs/linter/index.mdx
src/content/docs/reference/configuration.mdx

This PR documents `files.experimentalScannerIgnores`

feat: document scanner ignores option

---

src/content/docs/reference/zed.mdx

Fixed typo in docs for Zed editor extension.

Fix typo in zed docs

---

.github/workflows/schema.yml
Cargo.lock
Cargo.toml
codegen/src/lib.rs
codegen/src/main.rs
codegen/src/website.rs

This PR changes the `all` command to provide a `--online` argument that defaults to `true`. When `--online` is `true`, the CLI reads the changelog from githun.com, otherwise it reads it from the file system.
To avoid possible complications in the CI, this argument defaults to `true`.

chore: online changelog

---

src/content/docs/guides/getting-started.mdx

Hey ! While setting up biome on my project I noticed that the yarn script on `# Format, lint, and organize imports of all files` mentions `<files>`  which should not be here.
The others tabs (npm, pnpm...) don't have this so this PR removes it

Fix yarn check script (all files)

---

src/content/docs/guides/configure-biome.mdx

Fix a little docs mistake: any `includes` should always start with at least one non-exception pattern.

fix(configure-biome): add missing globstar in includes

---

src/content/docs/zh-CN/reference/reporters.mdx

This PR adds the Chinese (Simplified) translation for the `reporters.mdx` documentation page to improve accessibility for Chinese-speaking users.

docs: add zh-CN  for `reporters.mdx`

---

codegen/src/domains.rs
src/content/docs/guides/big-projects.mdx
src/content/docs/guides/configure-biome.mdx
src/content/docs/internals/architecture.mdx
src/content/docs/linter/domains.mdx
src/content/docs/linter/index.mdx
src/content/docs/reference/configuration.mdx

This reorganises and extends the scanner documentation, including the new "targeted" scanner behaviour.
Also added `nx.json` and `project.json` to the list of known files.

Extend scanner documentation

---

src/content/docs/es/recipes/git-hooks.mdx
src/content/docs/fr/recipes/git-hooks.mdx
src/content/docs/ja/recipes/git-hooks.mdx
src/content/docs/pt-BR/recipes/git-hooks.mdx
src/content/docs/recipes/git-hooks.mdx
src/content/docs/zh-CN/recipes/git-hooks.mdx

Currently, if one blinly copies the pre-commit config, it does not work. Bumping the versions makes it work.
Obviously, changing the version based on the version of the docs one looks at would be better, but I did not find such functionality in other parts of the codebase (maybe I looked in the wrong place) and before I reverse-engineer the whole system, just bumping the version seems simpler.

chore: bump the pre-commit version of biomejs that the docs recommend

---

src/content/docs/es/guides/manual-installation.mdx
src/content/docs/fr/guides/manual-installation.mdx
src/content/docs/guides/manual-installation.mdx
src/content/docs/ja/guides/manual-installation.mdx
src/content/docs/pt-BR/guides/manual-installation.mdx
src/content/docs/zh-CN/guides/manual-installation.mdx

This PR adds winget installation instructions to all language versions of the manual installation documentation, complementing the winget support recently introduced in [PR #6841](https://github.com/biomejs/biome/pull/6841).
- **Added winget installation section** to all `manual-installation.mdx` files across supported languages
- **Positioned consistently** after the Homebrew section in each file
- **Included proper formatting** with links to the winget package page
- **Used localized descriptions** for each language version
- ✅ `src/content/docs/guides/manual-installation.mdx` (English)
- ✅ `src/content/docs/fr/guides/manual-installation.mdx` (French)
- ✅ `src/content/docs/ja/guides/manual-installation.mdx` (Japanese)
- ✅ `src/content/docs/es/guides/manual-installation.mdx` (Spanish)
- …

docs: winget install instructions

---

.github/workflows/synchronize.yaml

The synchronize workflow will use the ref provided in the repository_dispatch payload. If the `next` branch is updated in the biomejs/biome repository, this workflow will sync it to the `next` branch in this repository.

ci: sync `next` branch from the main repo

---

codegen/src/lintdoc.rs

A small change to make it more immediately clear what nursery means.

docs: tweak the text that warns the user a rule is in nursery

---

codegen/src/lintdoc.rs

- The `middle_path` was marked as unused in the source code, which _causes issues with codegen_ and affects GitHub workflows.
- Remove `middle_path` entirely, as it is no longer needed.
- `codegen/src/lintdoc.rs`

fix(codegen): remove middle_path from lintdoc.rs

---

src/components/starlight/SiteTitle.astro
src/content.config.ts
src/content/i18n/en.json
src/content/i18n/ru.json

- Currently, components such as SiteTitle.astro cannot be localized.
- Add definitions for the used locale keys to `content.config.ts`
- Add locale files: `en.json` and `ru.json`
- `src/content.config.ts`
- `src/components/starlight/SiteTitle.astro`
- `src/content/i18n/en.json`
- `src/content/i18n/ru.json`
- In this pull request, SiteTitle.astro is used as an _example implementation of this feature_, so I can make any changes needed to improve it. Any feedback is welcome.

feat(components): implement localization support for SiteTitle.astro 

---

src/content/docs/guides/big-projects.mdx
src/content/docs/guides/configure-biome.mdx
src/content/docs/reference/configuration.mdx

This now works "properly" in 2.2.

docs: don't use `/**` to ignore folders

---

src/content/docs/linter/index.mdx

The suppression links in `/linter` weren't going to the right spot

fix supressions links

---

src/content/docs/recipes/continuous-integration.mdx

The example of how to integrate biome with gitlab-ci was outdated, this fixes the example code
- the **code-quality.json** needs to be passed as `artifacts.reports.codequality`
- the note about the `src` directory seems to be outdated as there is no reference to a `src` directory in the example-code

Fix example to integrate biomejs with gitlab-ci

---

src/content/docs/reference/configuration.mdx

Add a caution block regarding the usage of `!` to exclude directories in `files.includes`. The intent is to emphasize that using `!test` will work in `files.includes` and will exclude completely the `test` directory, but will not have that effect in other places where `includes` exists (like `linter`, `formatter`, etc.)
I'm suggesting this update because of https://github.com/biomejs/biome/issues/7262

docs: update `files.includes` doc

---

playwright.config.ts

This sets `workers` to the default value of `50%`. I think `0` previously did this, but it doesn't anymore.

chore(tests): tweak playwright config to let tests run locally

---

src/content/docs/es/guides/big-projects.mdx

Fixed some typos in the Spanish translation.

docs(es): fix typos

---

src/content/docs/reference/configuration.mdx

I was just checking out the docs and noticed the duplicate. I removed the one saying that the default is `true` since the HTML formatter is still experimental and whose description did not match the format of the other `*.formatter.enabled` entries.
Feel free to close this if I missed something and the duplication is intentional.

docs: remove duplicate `html.formatter.enabled`

---

src/content/docs/reference/configuration.mdx

Document that force-ignore syntax can be used to exclude special files such as `.gitignore` and nested `biome.json` files.
See https://github.com/biomejs/biome/pull/7444.

document behaviour of force-ignore on nested biome.json

---

src/components/Maintainers.astro
src/content/team.json

@vohoanglong0107 user doesn't exist on github anymore.
Also adding myself to the list.
I think team.json should be used to fill Maintainers, but I'm not sure how to do it in Astro.

fix: remove non-existent github user, add mdevils to the list of maintainers

---

codegen/src/lintdoc.rs

Companion for https://github.com/biomejs/biome/pull/7544
One of the parse errors was resolved by relaxing the CSS parser options, so we need to do the same here. I'm thinking we need to do even more code sharing here...

fix: resolve parse errors in ruledoc code blocks
