biomejs/website

- .github/CODEOWNERS
> chore: add CODEOWNERS to japanese translations

- .github/renovate.json
> chore: setup renovate

- .github/ISSUE_TEMPLATE/01_documentation.yml
- .github/ISSUE_TEMPLATE/config.yaml
> chore: add issue template

- .github/issue-labeler.yaml
- .github/pull-request-labeler.yaml
- .github/workflows/label-issue.yaml
- .github/workflows/label-pull-request.yaml
> chore: add issue and pr labeler

- netlify.toml
This PR adds the Netlify config.
> chore: add netlify config

- .github/workflows/update-contributors.yaml
- scripts/package.json
- scripts/update-contributors.js
- scripts/utils/argv.js
- scripts/utils/constants.js
Add update contributors workflow.
I changed the codegen task into a js script so we don't have to install the rust toolchain for this simple task :)
> chore(ci): setup update-contributors workflow

- .github/workflows/ja-translation.yaml
- .github/workflows/update-contributors.yaml
- package.json
> chore(ci): add checks for JA docs

- .github/workflows/update-contributors.yaml
We're already in the website's own repo. The message should be less verbose.
> chore(ci): change PR commit title

- Cargo.lock
- Cargo.toml
- codegen/Cargo.toml
- codegen/src/lib.rs
- codegen/src/lintdoc.rs
- codegen/src/main.rs
- codegen/src/website.rs
- src/content/docs/internals/changelog.md
This PR adds a script to generate the rest of the pages, AKA `generate_website.rs`
> chore: add script to generate website pages

- .github/workflows/update-linter-pages.yml
- README.md
- codegen/src/lib.rs
- codegen/src/main.rs
- codegen/src/website.rs
This PR adds a workflow that is triggered nightly, and it updates **only** the linter pages.
> ci: add workflow to update the linter pages

- .gitattributes
> fix: `.gitattributes` typos

- src/components/generated/Sources.md
- src/content/authors/conaclos.json
- src/content/blog/biome-v1-6.mdx
- src/content/blog/biome-v1-7.md
- src/content/docs/formatter/index.mdx
- src/content/docs/guides/getting-started.mdx
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/internals/language-support.mdx
- src/content/docs/ja/analyzer/index.mdx
- src/content/docs/ja/formatter/index.mdx
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/ja/internals/language-support.mdx
- src/content/docs/ja/recipes/git-hooks.mdx
- src/content/docs/pt-br/analyzer/index.mdx
- src/content/docs/pt-br/formatter/index.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/pt-br/internals/language-support.mdx
- src/content/docs/pt-br/recipes/git-hooks.mdx
- src/content/docs/recipes/git-hooks.mdx
- src/content/docs/reference/cli.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/analyzer/index.mdx
- src/content/docs/zh-cn/formatter/index.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/internals/changelog.mdx
- src/content/docs/zh-cn/internals/language-support.mdx
- src/content/docs/zh-cn/recipes/git-hooks.mdx
- src/pages/schemas/1.7.0/schema.json.js
I synced the website content with the main repo. If this is not the final transition, this PR still helps because of less diffs and a smoother transition later.
> chore: update the website content

- src/content/docs/ja/index.mdx
- src/content/docs/pt-br/index.mdx
- src/content/docs/zh-cn/index.mdx
While reading the Japanese documentation today, I noticed that the numbers of lint rules in each README are outdated.
I have updated them accordingly.
> Update number of lint rules

- src/content/docs/internals/changelog.md
- src/pages/schemas/1.7.1/schema.json.js
Update the website with the last release version of Biome.
> release: 1.7.1

- src/pages/schemas/1.7.0/schema.json.js
- src/pages/schemas/1.7.1/schema.json.js
Fix JSON schemas
Follow up of [biome#2568](https://github.com/biomejs/biome/pull/2568) and [biome#2567](https://github.com/biomejs/biome/pull/2567).
> docs: fix JSON schemas of last versions

- src/content/docs/guides/getting-started.mdx
Fixed a typo in the [Getting Started page](https://biomejs.dev/guides/getting-started/).
> Fix a typo in getting-started.mdx

- codegen/Cargo.lock
- codegen/src/lintdoc.rs
This PR fixes a regression in the generation of our rules
> fix: regression after recent changes

- README.md
- Add a github action badge in README to easily check the status of `Pin submodule and run codegen`.
- Fix a link in README.
> chore: small README improvements

- codegen/src/website.rs
Make the codegen script a bit more maintainable.
> chore(ci): refactor codegen script

- src/playground/workers/prettierWorker.ts
Closes https://github.com/biomejs/website/issues/53
> fix(playground): use correct JSON parser in prettier worker

- biome.json
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/pages/schemas/1.7.3/schema.json.js
Follow up https://github.com/biomejs/biome/pull/2722
> release: v1.7.3

- codegen/src/lintdoc.rs
I find that foreign code blocks usually fail the tests, so I introduced a `Foreign` code block type to treat those code blocks as is and avoid running tests on them.
> fix(codegen): support foreign code blocks

- src/content/docs/analyzer/import-sorting.mdx
> docs: side effect import sorting

- package.json
- pnpm-lock.yaml
Starlight 0.23.0 comes with performance gains
> chore: update starlight

- src/content/docs/zh-cn/guides/integrate-in-vcs.mdx
> fix(docs): typo

- src/content/docs/guides/how-biome-works.mdx
> docs: fix glob pattern docs

- src/playground/workers/biomeWorker.ts
Fix the playground issue introduced in #456.
> fix: pullDiagnostics

- src/content/docs/zh-cn/guides/how-biome-works.mdx
> fix: markdown typo in how-biome-works zh-cn

- src/content/docs/ja/recipes/git-hooks.mdx
- src/content/docs/pt-br/recipes/git-hooks.mdx
- src/content/docs/recipes/git-hooks.mdx
- src/content/docs/zh-cn/recipes/git-hooks.mdx
`npx biome` should be `npx @biomejs/biome`
> docs: update npx references

- .gitmodules
- Cargo.toml
- codegen/Cargo.toml
- codegen/src/lintdoc.rs
- codegen/src/metadata.rs
- rust-toolchain.toml
While working on https://github.com/biomejs/website/pull/435/, I did rebase some commits, and forgot to restore some changes.
This PR removes the git submodule.
> fix(codegen): regression

- .gitmodules
Revert the removal of the git submodule in #504
Hopefully, this allows the deployment of the website.
> fix: add biome submodule to allow the deplyement

- src/content/docs/guides/getting-started.mdx
- src/content/docs/reference/configuration.mdx
> refactor: update biome schema

- codegen/src/metadata.rs
- codegen/src/website.rs
- package.json
- src/content/docs/internals/changelog.md
This adds the codegen for v1.8.0
> fix: codegen

- .github/actions/run-codegen/action.yaml
Cargo puts the revision into the hash
> ci: revision should be the hash

- .github/actions/run-codegen/action.yaml
- codegen/Cargo.toml
I used some AI service to ask for the `awk` command to do global substitution. 
I used it locally and it worked.
> ci: use awk to update the Cargo.toml revision

- src/content/docs/reference/configuration.mdx
Document `css.parser.cssModules`
> feat: document CSS modules parsing

- .github/workflows/integrate.yaml
Use the GitHub reporter when running Biome.
> ci: use github reporter

- README.md
This PR adds a status Netlify badge
> feat: netlify badge

- src/content/docs/linter/index.mdx
Add some missing word in the docs
> fix: missing word

- codegen/src/website.rs
- src/pages/schemas/1.8.0/schema.json.js
Fix [bion#3098](https://github.com/biomejs/biome/issues/3098)
> fix: JSON schema for Biome 1.8

- scripts/update-revision.sh
I was using `sed` but changed to `awk`.
> chore(ci): fix comment

- astro.config.ts
- src/env.d.ts
- src/playground/components/BiomeHeader.tsx
- src/playground/components/PrettierHeader.tsx
- src/styles/playground/_tabs.scss
> feat(playground): display Biome and Prettier version

- .gitignore
- biome.json
- package.json
The `biome/**` was causing weird issue on my machine. After I deleted it, the scripts started to work again
Closes #533
> chore: update biome configuration and scripts

- src/components/starlight/SiteTitle.astro
> fix(css): unbalanced bracket

- astro.config.ts
- src/content/docs/recipes/badges.mdx
Adds a new page with the official shied badges :)
> feat: adds a new "Social badges" page

- src/content/docs/guides/big-projects.mdx
- src/content/docs/ja/guides/big-projects.mdx
- src/content/docs/pt-br/guides/big-projects.mdx
- src/content/docs/zh-cn/guides/big-projects.mdx
The enable property type is wrong in config example.
> fix: enable property type error in config example

- src/content/docs/formatter/index.mdx
took me some time to find out what I was needing
It's not tab width but indent width
> docs: format for better readability

- Cargo.lock
- Cargo.toml
- codegen/src/lintdoc.rs
- codegen/src/metadata.rs
- package.json
- pnpm-lock.yaml
- rust-toolchain.toml
https://github.com/biomejs/biome/pull/3222
> chore: bump rust to 1.79.0

- src/content/docs/guides/getting-started.mdx
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/pages/schemas/1.8.2/schema.json.js
> chore: release v1.8.2

- src/playground/workers/biomeWorker.ts
Fix a type issue that may break the playground.
> fix: graphql format output type

- src/content/docs/formatter/index.mdx
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/guides/migrate-eslint-prettier.mdx
- src/content/docs/ja/formatter/index.mdx
- src/content/docs/pt-br/formatter/index.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/formatter/index.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/playground/PlaygroundLoader.tsx
- src/playground/tabs/SettingsTab.tsx
- src/playground/types.ts
- src/playground/workers/biomeWorker.ts
- src/playground/workers/prettierWorker.ts
Migrate from the deprecated options to the new alternatives in our website.
> chore: use `trailingCommas` in our website

- src/playground/utils.ts
This is a follow-up fix of #647.
> fix: out-of-bounds access of code units

- .github/actions/run-codegen/action.yaml
- src/playground/utils.ts
The logic is borrowed from https://github.com/moonrepo/setup-rust/blob/dcab3dcf9f278945f3f983bace1c7c84033433a7/src/cargo.ts#L101-L153
> chore(ci): temporary fix cache

- Cargo.toml
- package.json
- pnpm-lock.yaml
This PR manually updates the playground. GraphQL linting now works!
> chore: manual update of the playground

- src/content/docs/guides/getting-started.mdx
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/reference/cli.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/pages/schemas/1.8.3/schema.json.js
> chore: release v1.8.3

- src/playground/workers/biomeWorker.ts
- src/playground/workers/prettierWorker.ts
> feat(playground): support for graphql formatting

- src/styles/playground/_tabs.scss
> fix: fix font in .formatter-version

- Cargo.lock
- Cargo.toml
- codegen/src/lintdoc.rs
- package.json
- pnpm-lock.yaml
- src/components/generated/NumberOfRules.astro
- src/content/docs/linter/rules-sources.mdx
- src/pages/metadata/rules.json.js
The script was broken because of the API change in https://github.com/biomejs/biome/pull/3275
> fix(ci): lintdoc

- src/content/docs/ja/recipes/git-hooks.mdx
- src/content/docs/pt-br/recipes/git-hooks.mdx
- src/content/docs/recipes/git-hooks.mdx
- src/content/docs/zh-cn/recipes/git-hooks.mdx
lefthook has an option (`stage_fixed`) for re-staging, and I think this setting is more concise and intuitive.
https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#stage_fixed
> docs: modify lefthook re-stage example

- src/content/docs/linter/index.mdx
The biome.json config was error when I copy/pasted, so I fixed according to the error.
> Update index.mdx biome.json config

- src/content/docs/ja/recipes/git-hooks.mdx
> docs: fix broken link

- src/content/docs/formatter/index.mdx
- src/content/docs/guides/big-projects.mdx
- src/content/docs/guides/getting-started.mdx
- src/content/docs/guides/how-biome-works.mdx
- src/content/docs/guides/integrate-in-editor.mdx
- src/content/docs/guides/integrate-in-vcs.mdx
- src/content/docs/guides/manual-installation.mdx
- src/content/docs/linter/index.mdx
This PR makes some fixes and proposes slight changes to improve readability.
I also added some details about a caveat of our glob library in the How-Biome-works guide.
> docs: improve guides

- src/content/docs/linter/index.mdx
This fix is intended to remove code and text inconsistencies
> Fix incorrect linter CLI example

- Cargo.lock
- Cargo.toml
- codegen/src/website.rs
`VERSION` is now exported by `biome_configuration`
> fix: version visibility

- codegen/src/rules_sources.rs
- src/content/docs/linter/rules-sources.mdx
- src/content/docs/linter/rules/index.mdx
> fix: exclude non-deployed rules from rule sources

- src/content/docs/formatter/differences-with-prettier.md
While reading the documentation, I noticed that the code samples have errors in displaying added and deleted lines. The motivation for these changes is to improve interaction with the documentation
> fix: incorrect del/ins displaying

- codegen/src/lintdoc.rs
- codegen/src/website.rs
- rust-toolchain.toml
> chore: update rust

- Cargo.lock
- Cargo.toml
- astro.config.ts
- codegen/src/diagnostics.rs
- codegen/src/lib.rs
- codegen/src/lintdoc.rs
- codegen/src/main.rs
- codegen/src/rules_sources.rs
- package.json
- src/components/generated/diagnostics/DiagnosticCategoryLink.md
- src/components/generated/diagnostics/DiagnosticCategorySimple.md
- src/components/generated/diagnostics/DiagnosticDeprecated.md
- src/components/generated/diagnostics/DiagnosticError.md
- src/components/generated/diagnostics/DiagnosticFatal.md
- src/components/generated/diagnostics/DiagnosticFixable.md
- src/components/generated/diagnostics/DiagnosticInformation.md
- src/components/generated/diagnostics/DiagnosticInternal.md
- src/components/generated/diagnostics/DiagnosticLocAll.md
- src/components/generated/diagnostics/DiagnosticLocFile.md
- src/components/generated/diagnostics/DiagnosticLocFrame.md
- src/components/generated/diagnostics/DiagnosticLocMultiline.md
- src/components/generated/diagnostics/DiagnosticVerbose.md
- src/components/generated/diagnostics/DiagnosticWarning.md
- src/components/generated/diagnostics/DiagnosticWithAdvice.md
- src/content/docs/guides/diagnostics-anatomy.mdx
- src/content/docs/index.mdx
- src/content/docs/ja/index.mdx
- src/content/docs/pt-br/index.mdx
- src/content/docs/reference/diagnostics.mdx
- src/content/docs/zh-cn/index.mdx
This PR adds a new page that explains our diagnostics :)
> feat: add a page to describe diagnostics

- src/styles/_patches.scss
This is an experiment to see whether reducing the size of the headings improves readability.
> feat: make heading sizes smaller

- src/playground/workers/biomeWorker.ts
It's weird that we didn't catch this.
Anyway, this should fix the issue
> fix(wasm): regression

- package.json
- pnpm-lock.yaml
- src/playground/utils.ts
- src/playground/workers/biomeWorker.ts
- src/playground/workers/prettierWorker.ts
> feat: add support for html, vue, and svelte files in the playground

- src/playground/workers/biomeWorker.ts
CI was failing because of formatting.
> chore: format to fix ci

- Cargo.lock
- Cargo.toml
- codegen/src/lintdoc.rs
Should fix the sync PRs failing.
> chore: manually synchronize to `7ffc53f`

- src/content/docs/internals/language-support.mdx
Since I've started work on the formatter, I figured I'd update the status here.
> chore: mark html formatter as in progress

- src/content/blog/biome-v1-9.md
> Fix "migrate" typo

- src/content/docs/linter/rules/no-global-eval.mdx
Fixes the never use direct eval link
> fix(docs): update no-global-eval link

- astro.config.ts
- src/content/docs/guides/editors/create-a-extension.mdx
- src/content/docs/guides/editors/first-party-extensions.mdx
- src/content/docs/guides/editors/third-party-extensions.mdx
- src/content/docs/reference/zed.mdx
- Added a new page `/reference/zed`. 
- Renamed the editor plugins page to editor **extensions**
- Added the reference links to the extension pages
> feat: add zed extension page

- src/content/docs/ja/recipes/continuous-integration.mdx
Translates a section "Third-party actions" to Japanese.
> docs(ja): translate third-party actions

- rust-toolchain.toml
This should fix the synchronize job.
> chore: update rust to 1.81

- src/pages/schemas/1.6.0/schema.json.js
- src/pages/schemas/1.6.1/schema.json.js
- src/pages/schemas/1.6.2/schema.json.js
- src/pages/schemas/1.6.3/schema.json.js
- src/pages/schemas/1.6.4/schema.json.js
- src/pages/schemas/1.7.0/schema.json.js
- src/pages/schemas/1.7.1/schema.json.js
- src/pages/schemas/1.7.2/schema.json.js
- src/pages/schemas/1.7.3/schema.json.js
- src/pages/schemas/1.8.0/schema.json.js
- src/pages/schemas/1.8.1/schema.json.js
- src/pages/schemas/1.8.2/schema.json.js
- src/pages/schemas/1.8.3/schema.json.js
- src/pages/schemas/1.9.0/schema.json.js
- src/pages/schemas/1.9.1/schema.json.js
- src/pages/schemas/1.9.2/schema.json.js
Related to https://github.com/biomejs/biome/pull/4080
> fix(schema): make optional the JSON schema field options

- src/playground/workers/biomeWorker.ts
Fixed `biome check` error on main branch.
- any type error
- formatting
> fix: `biome check` error

- .github/workflows/playwright.yml
- .gitignore
- package.json
- playwright.config.ts
- pnpm-lock.yaml
- src/playground/Playground.tsx
- src/playground/tabs/FormatterCodeTab.tsx
- src/playground/tabs/FormatterIrTab.tsx
- src/playground/tabs/SettingsTab.tsx
- src/playground/tabs/SyntaxTab.tsx
- tests/playground/smoke.spec.ts
The playground keeps breaking for very preventable reasons. This adds some playwright tests to make sure it stays working.
> test(playground): add e2e smoke tests for playground

- src/content/docs/formatter/index.mdx
- src/content/docs/reference/configuration.mdx
> docs: document editorconfig configuration

- src/components/generated/DefaultConfiguration.mdx
- src/content/docs/guides/configure-biome.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/ja/reference/configuration.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/pages/schemas/1.9.3/schema.json.js
> release: v1.9.3

- biome.json
- codegen/src/metadata.rs
- src/pages/metadata/rules.json.js
- src/pages/metadata/schema.json.js
That was requested in https://github.com/SrBrahma/eslint-config-biome/issues/5#issuecomment-2396451086
> chore: export metadata for `rules.json`

- biome.json
- src/components/generated/DefaultConfiguration.mdx
- src/content/docs/guides/configure-biome.mdx
- src/content/docs/internals/changelog.md
- src/content/docs/ja/guides/getting-started.mdx
- src/content/docs/ja/reference/configuration.mdx
- src/content/docs/pt-br/guides/getting-started.mdx
- src/content/docs/reference/configuration.mdx
- src/content/docs/zh-cn/guides/getting-started.mdx
- src/content/docs/zh-cn/reference/configuration.mdx
- src/pages/schemas/1.9.4/schema.json.js
Follow up of https://github.com/biomejs/biome/pull/4320
> release: v1.9.4

- src/content/docs/internals/changelog.md
> chore: update changelog

- codegen/src/diagnostics.rs
- codegen/src/env_variables.rs
- codegen/src/lintdoc.rs
- codegen/src/rules_sources.rs
> style: simplify string formatting for readability

- codegen/src/lintdoc.rs
> refactor: remove unnecessary explicit deref

- src/content/docs/internals/changelog.md
> chore: update changelog title

- codegen/src/env_variables.rs
> refactor: remove unnecessary `static`

- src/content/docs/guides/editors/first-party-extensions.mdx
Also fixed instructions for IntelliJ (mainly renaming extension -> plugin)
Fixes broken link and corrects documentation for IntelliJ
> Fixing broken link and fixing IntelliJ documentation

- src/content/docs/guides/editors/create-a-extension.mdx
> Fix broken link

- src/content/docs/guides/editors/third-party-extensions.mdx
> Update outdated link

- src/content/docs/reference/configuration.mdx
> add VCS notation

- src/content/docs/internals/language-support.mdx
- src/content/docs/ja/internals/language-support.mdx
- src/content/docs/pt-br/internals/language-support.mdx
- src/content/docs/zh-cn/internals/language-support.mdx
Align language support table for foreign locales, remove linked issues as GraphQL is done, but link issue to markdown
> docs: small fixes in the language support table

- astro.config.ts
The `astronomical.config.ts` is updated to add the locale for the French translation and the translations of sidebar labels into French.
> docs: update config with French translation support

- src/content/docs/fr/404.md
Add the translation into French of the website 404 page.
Added:
- the `404.md` file translated into French.
> docs: add French translation of 404.md

- astro.config.ts
> chore: remove adapter

- astro.config.ts
- lunaria.config.json
- package.json
- pnpm-lock.yaml
- src/content/docs/ja/guides/getting-started.mdx
Closes #1597 
I will revert the content change once the CI passes
> chore: different root dir

- src/content/docs/ja/reference/zed.mdx
This PR adds a Japanese translation doc for the Zed extension.
> docs(ja): Zed extension

- src/styles/_overrides.css
I forgot to fix the "Commercial support" link in the card on the homepage. It works now.
> Fix links in cards

- astro.config.ts
- src/components/starlight/SiteTitle.astro
- src/content/docs/index.mdx
- src/pages/enterprise.astro
Updated the wording to use "Enterprise" instead of just "Support".
> Support => Enterprise

- src/content/docs/blog/roadmap-2025.md
Proposed roadmap for 2025, including our plans for Biome 2.0. Please review and let me know if I missed anything!
> Roadmap 2025

- src/playground/tabs/DiagnosticsListTab.tsx
This is a simple PR to make it a little more clear where diagnostics are coming from in the playground. While this info is already available in the `Console` tab, this makes it immediately obvious at first glance.
> feat(playground): display diagnostic category

- src/playground/Playground.tsx
- src/playground/tabs/AnalyzerFixesTab.tsx
- src/playground/tabs/SettingsTab.tsx
- src/playground/types.ts
- src/playground/workers/biomeWorker.ts
This PR adds a new tab to preview analyzer fixes. Open to suggestions for naming things.
closes #1052
> feat(playground): add tab to preview analyzer fixes

- rust-toolchain.toml
I ran the synchronize workflow manually and got this: https://github.com/biomejs/website/actions/runs/13289835490/job/37107548385
I'm pretty sure this will fix that error.
> chore: update rust to 1.84.0

- astro.config.ts
- src/content/docs/ja/assist/index.mdx
This pull request adds a translation of the new Assist feature documentation for Japanese.
> feat(i18n): add translation of Assist for Japanese

- src/content/docs/ja/assist/index.mdx
Follow-up of #1745 
I applied `textlint --fix` to the added page.
> fix(i18n): styling fix based on textlint for Japanese

- .github/renovate.json
- .textlintrc.json
- biome.json
- lunaria.config.json
- scripts/package.json
- tsconfig.json
Cherry-picks 1bdfe378d1886aded68a1a700d64623db2e03404 from the `next` branch to make CIs happy :)
> chore: use spaces for json

- src/content/docs/blog/biome-v1-7.md
- src/content/docs/blog/biome-v1-9.md
- src/content/docs/blog/biome-wins-prettier-challenge.md
- src/content/docs/blog/roadmap-2024.md
- src/content/docs/guides/integrate-in-vcs.mdx
Markdown was broken in few places and shown syntax instead of its effect
> fix markdown format

- src/content/docs/internals/language-support.mdx
Closes https://github.com/biomejs/website/issues/1756
> feat: add grit to the supported languages

- src/content/docs/reference/configuration.mdx
closes: #1823
The mr link is: https://github.com/biomejs/biome/pull/5127
> chore: update formatter.useEditorconfig

- src/content/docs/zh-CN/recipes/git-hooks.mdx
I fixed some translation errors.
> docs: update Chinese translation of recipes/git-hooks.mdx

- src/content/docs/internals/language-support.mdx
Add plugin support to the language support table.
> Plugin language support

- codegen/src/lintdoc.rs
- src/components/generated/assist/NumberOfRules.astro
- src/content/docs/assist/actions/organize-imports.mdx
- src/content/docs/assist/actions/use-sorted-attributes.mdx
- src/content/docs/assist/actions/use-sorted-keys.mdx
- src/content/docs/assist/actions/use-sorted-properties.mdx
- src/content/docs/assist/javascript/actions.mdx
- src/content/docs/assist/javascript/sources.mdx
This PR fixes the codegen for assist actions, and adds the organize imports
> chore: document organize imports, and fix codegen

- astro.config.ts
- src/content/docs/analyzer/plugins.mdx
- src/content/docs/blog/biome-v2-0-beta.md
- src/content/docs/guides/migrate-eslint-prettier.mdx
- src/content/docs/index.mdx
- src/content/docs/reference/gritql.mdx
Also added plugin documentation, partially as a teaser for people to try out the beta.
Please make sure I didn't forget anything important!
~~TODO: @dyc3 Could you write a small piece about the HTML formatter? I'm less sure about the state it is in, or what people need to do to try it out.~~ **Update:** Done!
> Beta blog post

- src/components/starlight/LanguageSelect.astro
Follow-up of #1865 
Let's update the default value on the next branch.
> feat: update the default value of the version selector

- src/content/docs/blog/biome-v2-0-beta.md
We were in the future, let's back to the present :)
> fix(blog): update the published date of the blog post

- src/content/docs/blog/biome-v2-0-beta.md
> chore: fix typo in blog

- src/pages/schemas/2.0.0-beta.1/schema.json.js
Adds the `2.0.0-beta.1` schema
> chore: add beta schema

- astro.config.ts
- src/content/docs/ja/linter/plugins.mdx
Added Japanese translation for the new plugins docs.
> feat(i18n): add Japanese translation for plugins docs

- codegen/src/domains.rs
- src/content/docs/linter/domains.mdx
- src/content/docs/linter/index.mdx
Closes https://github.com/biomejs/website/issues/1925
> fix: correct configuration for domains

- src/content/docs/fr/reference/configuration.mdx
Add the translation into French of the Configuration page.
Added:
- the `reference/configuration.mdx` file translated into French.
> docs: add French translation of reference/configuration.mdx

- astro.config.ts
- src/components/starlight/Footer.astro
- src/content/docs/blog/vercel-partners-biome-type-inference.md
New blog post about our partnership/sponsorship.
Added a footer to all the website pages for our platinum sponsorship.
> Vercel partnership

- Cargo.lock
- Cargo.toml
- package.json
> Rename dependency graph

- astro.config.ts
- src/content/docs/es/analyzer/import-sorting.mdx
- src/content/docs/es/analyzer/index.mdx
add analyzer section for Spanish i18n (#2018)
> docs: add spanish i18n analyzer section

- src/content/docs/es/404.md
Adding 404 page i18n for Spanish (#2018)
> docs: add 404 spanish I18n

- astro.config.ts
- src/content/docs/es/formatter/differences-with-prettier.md
- src/content/docs/es/formatter/index.mdx
- src/content/docs/es/formatter/option-philosophy.md
Adding formatter section for Spanish i18n (#2018)
> docs: add spanish i18n formatter section

- astro.config.ts
- src/content/docs/es/internals/architecture.mdx
- src/content/docs/es/internals/changelog.md
- src/content/docs/es/internals/credits.mdx
- src/content/docs/es/internals/language-support.mdx
- src/content/docs/es/internals/philosophy.mdx
- src/content/docs/es/internals/versioning.mdx
Adding internals section for Spanish i18n (#2018)
> docs: add spanish i18n internals section

- astro.config.ts
- src/content/docs/es/recipes/badges.mdx
- src/content/docs/es/recipes/continuous-integration.mdx
- src/content/docs/es/recipes/git-hooks.mdx
- src/content/docs/es/recipes/renovate.mdx
Adding recipes section Spanish i18n (#2018)
> docs: add spanish i18n recipes section

- astro.config.ts
- src/content/docs/es/linter/index.mdx
- src/content/docs/es/linter/plugins.mdx
Adding linter section for Spanish i18n (#2018)
> docs: add spanish i18n linter section

- .github/workflows/integrate.yaml
- .github/workflows/ja-translation.yaml
- .github/workflows/label-issue.yaml
- .github/workflows/label-pull-request.yaml
- .github/workflows/lunaria.yml
- .github/workflows/playwright.yml
- .github/workflows/run-codegen.yaml
- .github/workflows/synchronize.yaml
- .github/workflows/update-contributors.yaml
This PR changes the CI workflows to use depot runners
> ci(workflow): use depot runners

- astro.config.ts
- src/content/docs/es/guides/big-projects.mdx
- src/content/docs/es/guides/configure-biome.mdx
- src/content/docs/es/guides/editors/create-a-extension.mdx
- src/content/docs/es/guides/editors/first-party-extensions.mdx
- src/content/docs/es/guides/editors/third-party-extensions.mdx
- src/content/docs/es/guides/getting-started.mdx
- src/content/docs/es/guides/integrate-in-vcs.mdx
- src/content/docs/es/guides/manual-installation.mdx
- src/content/docs/es/guides/migrate-eslint-prettier.mdx
Adding guides section for Spanish i18n (#2018)
> docs: add spanish i18n guides section

- astro.config.ts
- src/content/docs/es/reference/cli.mdx
- src/content/docs/es/reference/configuration.mdx
- src/content/docs/es/reference/diagnostics.mdx
- src/content/docs/es/reference/gritql.mdx
- src/content/docs/es/reference/reporters.mdx
- src/content/docs/es/reference/vscode.mdx
- src/content/docs/es/reference/zed.mdx
Adding reference section for Spanish i18n (#2018)
> docs: add spanish i18n reference section

- src/playground/Playground.tsx
- src/playground/tabs/TypeInfoTab.tsx
- src/playground/tabs/TypesRegisteredTab.tsx
- src/playground/types.ts
- src/playground/workers/biomeWorker.ts
New tabs available:
- Types IR
- Types registered 
These new tabs will be very useful to us as debugging tool :)
> feat: types IR and types registration

- src/pages/schemas/2.0.0-beta.3/schema.json.js
> feat: add beta 3 schema

- codegen/src/domains.rs
- src/content/docs/linter/domains.mdx
- src/content/docs/reference/configuration.mdx
Explain behaviour of the scanner under the `files.includes` docs.
> Scanner docs

- src/content/docs/linter/index.mdx
This PR adds a new question in the FAQ section of the linter regarding the performance penalty of certain rules.
> chore: add faq for performance

- src/content/docs/blog/annoucing-biome.mdx
- src/content/docs/blog/biome-v1-5.md
- src/content/docs/blog/biome-v1-6.mdx
- src/content/docs/blog/biome-v1-7.md
- src/content/docs/blog/biome-v1-9.md
- src/content/docs/blog/biome-v1.mdx
- src/content/docs/blog/biome-v2-0-beta.md
- src/content/docs/blog/biome-wins-prettier-challenge.md
- src/content/docs/blog/roadmap-2024.md
- src/content/docs/blog/roadmap-2025.md
- src/content/docs/blog/vercel-partners-biome-type-inference.md
It makes our `/blog` page a bit more bearable :)
> feat: use excerpt as summaries

- src/content/docs/reference/vscode.mdx
This PR updates the VS Code reference to reflect the changes that were made in the upcoming final release of the v3 extension.
> docs: update vs code reference

- src/content/docs/linter/index.mdx
Added a FAQ that explains the status quo of the current memory usage
> chore: add FAQ for memory usage

- astro.config.ts
- src/content/docs/guides/big-projects.mdx
- src/content/docs/reference/configuration.mdx
This PR updates the Big Projects page with a small tutorial on how users can set up a monorepo. It also updates the configuration reference.
> feat: document monorepo

- astro.config.ts
- src/content/docs/ja/reference/vscode.mdx
Fixed typos in Japanese documentation(VSCode -> VS Code).
> docs(ja): fix typo

- codegen/src/domains.rs
This should also un-break the synchronization with the main repo.
> fix(codegen): don't render domains with no rules, make adding new domains have less friction

- package.json
- pnpm-lock.yaml
- src/content/docs/reference/configuration.mdx
> fix: improve negated pattern instructions

- src/content/docs/blog/biome-v1-5.md
- src/content/docs/blog/biome-v1-9.md
- src/content/docs/blog/biome-v2.mdx
- src/content/docs/blog/biome-wins-prettier-challenge.md
- src/content/docs/index.mdx
- src/content/docs/internals/changelog_v1.md
- src/content/docs/pt-BR/guides/getting-started.mdx
- src/content/docs/pt-BR/index.mdx
- src/content/docs/uk/index.mdx
- src/content/docs/zh-CN/guides/getting-started.mdx
- src/content/docs/zh-CN/index.mdx
Fix some broken links, notably the linter rules link.
Also, I added HTML in the list of formatted languages.
> fix: broken links

- src/components/PackageManagerBiomeCommand.astro
- src/components/PackageManagerCommand.astro
- src/content/docs/guides/getting-started.mdx
- src/content/docs/internals/versioning.mdx
This PR improves the Getting Started page for better readability. It conveys the same information in a more concise and approachable way.
The installation commands have been shortened.
Frames and line numbers around code fences have been hidden to make them feel less busy.
_This change affects the whole site, as intended._
The main Biome commands have been grouped into an overview code fence, so they take less space overall.
> feat: improve getting started docs

- src/content/docs/guides/big-projects.mdx
- src/content/docs/internals/people-and-credits.mdx
Related to https://github.com/biomejs/biome/pull/6378
> chore: document monorepo limitations

- codegen/src/lintdoc.rs
- codegen/src/metadata.rs
- codegen/src/rules_sources.rs
Follow up of https://github.com/biomejs/biome/pull/6556#pullrequestreview-2961568687
> refactor: update code to the new rule source metadata

- codegen/src/metadata.rs
- codegen/src/rules_sources.rs
Foolow up of https://github.com/biomejs/website/pull/2543
> fix: lint and compile errors

- .github/workflows/schema.yml
- codegen/src/main.rs
This PR adds a new workflow to automate the generation of the file we usually do after the release:
- rules
- schema
- other files in general
> ci: workflow for the release

- src/playground/CodeMirror.tsx
> fix(playground): gracefully handle null spans in diagnostics

- src/components/PackageManagerBiomeCommand.astro
- src/components/PackageManagerCommand.astro
- src/content/docs/blog/biome-v2-1.mdx
- src/content/docs/guides/getting-started.mdx
- src/content/docs/guides/upgrade-to-biome-v2.mdx
Added blog post for 2.1 release.
Please proofread, and see if I have missed anything noteworthy.
> Add blog post for 2.1

- astro.config.ts
- src/content/docs/guides/investigate-slowness.mdx
- src/content/docs/linter/index.mdx
Resolves https://github.com/biomejs/website/issues/2671.
> Add guide for investigating slowness

- src/components/Sponsors.astro
- src/components/starlight/Footer.astro
> chore: remove platinum sponsor

- src/components/Sponsors.astro
> refactor: remove unused imports in Sponsors.astro

- src/content/docs/guides/upgrade-to-biome-v2.mdx
It wasn't unintelligible before, but using idiomatic English [word/phrase ordering](https://en.wikipedia.org/wiki/Object%E2%80%93subject%E2%80%93verb_word_order) should improve readability
> docs: use idiomatic English ordering

- codegen/src/lintdoc.rs
The code blocks in rule docs with `json,options` tags have a special convention.
```json
{
"options": {
"foo": "bar"
}
}
```
will be translated into:
```json
{
"linter": {
"rules": {
"<group>": {
"<rule>": {
"options": {
"foo": "bar"
}
}
}
}
}
}
```
However, this won't work for assist actions as it should be translated into `assist.actions.<group>.<rule>.options` instead, otherwise it cannot be deserialised into valid options.
> fix(codegen): support `use_options` convention in assist actions

- src/content/docs/guides/big-projects.mdx
> Invalid json example in big projects

- src/content/docs/analyzer/suppressions.mdx
> docs: fix the explanation of suppression with values

- src/content/docs/ru/index.mdx
- Add `src/content/docs/ru/index.mdx`
- `src/content/docs/ru/index.mdx`
- Does `public/_redirects` need to be updated in order to redirect 404s to a localized page?
- Is it intended that components such as `SiteTitle.astro` cannot be localized, or can I implement this?
> docs(ru): add index.mdx

- public/_redirects
- Add 404 redirect rule (`/ru/* /ru/404 404`) for Russian language
- `public/_redirects`
> chore(docs): add 404 redirect rule for /ru in public/_redirects

- src/content/docs/internals/architecture.mdx
- src/content/docs/linter/index.mdx
- src/content/docs/reference/configuration.mdx
To be merged when https://github.com/biomejs/biome/pull/6989 is released.
> docs: scanner updates

- astro.config.ts
- src/components/starlight/SiteTitle.astro
- src/content/i18n/ja.json
Updated translations of menu items.
I also fixed the "Docs" link in the navbar not navigating to the localised page.
> feat(ja): update menu translations

- src/content/docs/es/recipes/continuous-integration.mdx
- src/content/docs/fr/recipes/continuous-integration.mdx
- src/content/docs/ja/recipes/continuous-integration.mdx
- src/content/docs/pt-BR/recipes/continuous-integration.mdx
- src/content/docs/recipes/continuous-integration.mdx
- src/content/docs/zh-CN/recipes/continuous-integration.mdx
Small update on suggested gh actions workflows. (https://github.com/zizmorcore/zizmor great tool to find such issues)
- update checkout action to v5
- Remove persisted credentials when not needed
> docs: improve suggested gh actions

- src/content/docs/reference/vscode.mdx
- src/content/docs/reference/zed.mdx
There were reports where people can't find a way to turn a code fix into a safe code fix. People suggested to expand the editor configuration pages
> feat: improve editor docs

- src/content/docs/reference/configuration.mdx
docs PR for https://github.com/biomejs/biome/pull/7164
> docs: add `css.parser.tailwindDirectives`

- src/content/docs/fr/reference/configuration.mdx
Update the french translation for the configuration section in order to match the v2.
Will fix: https://github.com/biomejs/website/issues/2973
> feat(fr): update french configuration section

- src/content/docs/reference/configuration.mdx
- Removed outdated `overrides.<ITEM>.organizeImports` entry
- Made the other overrides entries follow more natural english semantics, and minor elaborations.
> docs: misc updates to overrides configuration

- astro.config.ts
- src/content/docs/pt-BR/guides/configure-biome.mdx
Updates the Portuguese (Brazil) translation of the configure-biome guide.
- Updated content to match latest English version
- Fixed outdated information
> docs(pt-BR): update configure-biome guide

- src/content/docs/pt-BR/guides/big-projects.mdx
Updates the Portuguese (Brazil) translation of the big-projects guide.
- Updated content to match latest English version
- Fixed outdated information
> docs(pt-BR): update big-projects guide

- astro.config.ts
- src/content/docs/pt-BR/guides/integrate-in-vcs.mdx
Updates the Portuguese (Brazil) translation of the integrate-in-vcs guide.
- Updated content to match latest English version
- Fixed outdated information
> docs(pt-BR): update integrate-in-vcs guide

- src/content/docs/reference/zed.mdx
> Added lsp parent to config example

- src/content/docs/reference/configuration.mdx
> docs: add missing example for javascript.formatter.quoteStyle

- src/content/i18n/pl.json
This pull request adds the Polish translation for `src/content/i18n`.
> docs(pl): translation for header categories

- src/content/docs/pl/404.md
This pull request adds the Polish translation for `src/content/docs/404.md`.
> docs(pl): translation for 404.md
